### PR TITLE
added options for customize the path

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? What's you use-case?

**Comment by Kikobeats** [comment]
temporal files in servers. Commonly servers as Amazon Services provide a Filesystem path for store irrelevant data that is separated of the os path. In the other hand, I need to store this temporal files in other side that is not the current os path.

The prefix path is to control with folders where is the data.

**Comment by Kikobeats** [comment]
ops, little fail: if you specify a `prefixpath` need to be sure that the folder exists. something like `mkdir -p` before. But first I need to know if you are interested :)

**Comment by jprichardson** [comment]
I like this, but I don't think that the path needs to be created if you specify pass in a path. As the user of the module, if your passing in a path, it should be your responsibility to ensure that it exists.

**Comment by ArtskydJ** [comment]
Perhaps for backwards compatibility, if `params` is a string, it is the extension.

**Comment by sindresorhus** [comment]
Thanks, but you're better off creating a new module. This is something I would never need, so I would prefer not bloating this super simple module with it ;)

**Comment by Kikobeats** [comment]
No problem. Bumped in [tempfile2](https://github.com/Kikobeats/tempfile2) :-)

**Pull request closed without merging**
